### ISSUE TITLE
Would like to contribute but don't know where to start.

### ISSUE THREAD

**Issue by BE-Webdesign** [xwp/wp-customize-widgets-plus#43]
@westonruter After reviewing a lot of your tickets and what not, I think this is a great Idea and would like to help out.  Could you point me towards a good starting direction for any issues I can help tackle.  I will start to navigate on my own but if you could give me a good starting point it would be greatly appreciated.  Thank you.

**Comment by westonruter** [comment]
This plugin is a bit of a grab bag of prototypes and features that I think should/could be considered for core. I don't have any specific starting point, other than something that scratches an itch you have.
