### ISSUE TITLE
Duplicate/Clone Widgets inside Customizer

### ISSUE THREAD

**Issue by towfiqi** [xwp/wp-customize-widgets-plus#44]
@westonruter Is it possible to duplicate widgets inside Customizer? I am an author of a free theme and users often ask whether they can clone widgets in Customizer. Although there are plenty of plugins out there that can clone widget in Appearance > Widgets but they do not work inside Appearance >  Customize. 

So my question is, Is it possible to clone widgets inside Customizer using the widget customizer api? May this objective fall under the scope of "wp-customize-widgets-plus"?

 If so, can you kindly point me into a direction/code that will help me achieve that.

Many Thanks for your contribution to WordPress. I am really grateful. :)

**Comment by westonruter** [comment]
Hi @towfiqi: duplicating widgets inside the Customizer is beyond the scope of this plugin. However, it can be done programmatically via something like this:

``` js
srcWidgetId = 'search-2';
matches = srcWidgetId.match( /(.+)-(\d+)/ );
sourceWidgetSettingId = 'widget_' + matches[1] + '[' + matches[2] + ']';
idBase = matches[1];
sidebarControl = wp.customize.control('sidebars_widgets[sidebar-1]');
destWidgetControl = sidebarControl.addWidget( idBase );
destWidgetControl.setting.set( wp.customize( sourceWidgetSettingId ).get( sourceWidgetSettingId ) );
```

**Comment by towfiqi** [comment]
@westonruter Many Thanks You are a lifesaver!! :) Sad thing is there is not widgets-ready event as requested [here](https://core.trac.wordpress.org/ticket/31320) . I had to wrap around the code with a settimeout function as _defer function is not working.

**Comment by westonruter** [comment]
Why do you need a widgets-ready event? What is the context for this?

**Comment by towfiqi** [comment]
Here is a the code I am currently using to add a duplicate button beside the close button in each widget. when you click the button the widget will be duplicated:

``` js
//DUPLICATE WIDGETS
jQuery( document ).on( 'load widget-added', function(event, widget) {

    //Append The duplicate button
    jQuery('.widget-control-actions').each(function(index, element) {
        if(jQuery(this).find('.optimizer_duplicate_widget').length == 0){
            jQuery(this).find('.widget-control-close').before('<a class="optimizer_duplicate_widget">Duplicate</a>');
        }
    });
});


jQuery( document ).on('load ready', function() {
    setTimeout(function(){
        //Duplicate Function
        jQuery('.optimizer_duplicate_widget').one('click',function(event) {
            rawsidebarid = jQuery(this).parent().parent().parent().parent().parent().parent().parent().parent().attr('id');
            rawidgetid = jQuery(this).parent().parent().parent().parent().parent().parent().attr('id');

            dsidebarid = rawsidebarid.split('accordion-section-sidebar-widgets-')[1];
            dwidgetid = rawidgetid.split('customize-control-widget_')[1];

            //console.log(dsidebarid); console.log(dwidgetid);
            srcWidgetId = ''+dwidgetid+'';
            matches = srcWidgetId.match( /(.+)-(\d+)/ );
            sourceWidgetSettingId = 'widget_' + matches[1] + '[' + matches[2] + ']';
            idBase = matches[1];
            sidebarControl = wp.customize.control('sidebars_widgets['+dsidebarid+']');
            destWidgetControl = sidebarControl.addWidget( idBase );
            destWidgetControl.setting.set( wp.customize( sourceWidgetSettingId ).get( sourceWidgetSettingId ) );
            wp.customize.control.each( function ( control ) {  if(control.expanded) control.collapse();  });
            destWidgetControl.focus();
        });
    }, 9000);

});
```

When you use this code without setTimeout function you will notice that the code doesn't run at all, because the click function initialize before the widgets are ready. I tried to make the click function depend on `widget-added` event, but that makes the click function run twice or thrice. Then I tried `wp.customize.previewer.bind` and `wp.customize.bind( 'ready', _.defer( function() {` they didn't work too. The only way it worked is when I wrapped the code around with settime with 9 seconds. Which is really unstable, because if the page loads after 9 seconds the function wont work. Hope you understand the issue. And pardon me if I have made any stupid mistakes in my code. 

Many Thanks for time :)

**Comment by westonruter** [comment]
The problem is that you're not using event delegation. Do this:

``` diff
- jQuery( document ).on('load ready', function() {
-     setTimeout(function(){
-         //Duplicate Function
-         jQuery('.optimizer_duplicate_widget').one('click',function(event) {
+ jQuery( '#customize-controls' ).on( 'click', '.optimizer_duplicate_widget', function(event) {
```

You could use event delegation like this or attach the click handler in the `widget-added` event.

**Comment by towfiqi** [comment]
@westonruter Thanks for your input, but it doesn't work either.. :cry:

**Comment by westonruter** [comment]
Well in spite of there being a bug somewhere, that's the overall approach you should take: use the `widget-added` event to add the button and (optionally) event delegation to listen for clicks. It will work and I've done it that way before. See also Jetpack's Widget Visibility functionality and how it adds buttons to widget controls: https://github.com/Automattic/jetpack/blob/master/modules/widget-visibility/widget-conditions/widget-conditions.js
